### ISSUE TITLE
Different fingerprint IDs in Firefox 106.0.1 / incognito

### ISSUE THREAD

**Issue by denikod** [Joe12387/OP-Fingerprinting-Script#2]
Hello!
I found that in Firefox v106.0.1 in normal mode and incognito mode, the resulting FingerPrint ID is different.

Comparing the output, I see that this is due to a different set of fonts and doNotTrack value:

**In normal mode, this is:**
`    "doNotTrack": [0, "unspecified"]`

**In incognito it is:**
`    "doNotTrack": [0, "1"],`
and fonts are similar to normal mode plus the following:
```
            "Arial Black",
            "Arial Narrow",
            "Bodoni MT Condensed"
```

You asked to report similar behavior ;-)

_And one more thing, in Chrome, when the console is open, the code stops at the following lines:_
```
#260 throw new Error("Max monochrome value is over 100");
#566 let enabled = ap.canMakePayments();
```
_It would be nice if this could be avoided..._

**have a great day!**

**Comment by Joe12387** [comment]
Thanks for the report! I think I've covered the issues you're experiencing with Firefox. I'm unsure if the fixes for Chrome will work as I cannot replicate the errors there.
